apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-frontend-dynamic-feature-loader
  title: "@backstage/frontend-dynamic-feature-loader"
spec:
  lifecycle: experimental
  type: backstage-web-library
  owner: maintainers
