app:
  experimental:
    packages:
      include:
        - '@backstage/frontend-dynamic-feature-loader'
        - '@backstage/plugin-app-visualizer'
        - '@backstage/plugin-catalog'
        - '@backstage/plugin-scaffolder'
        - '@backstage/plugin-search'
        - '@backstage/plugin-home'
  extensions:
    - page:home:
        config:
          path: '/'
